server:
  #  port: 8081
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.cloud.client.port}:${server.port}:${random.value}
    instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
