server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
  server:
    # enable-self-preservation: false # 关闭自我保护，生产环境不建议配置
    eviction-interval-timer-in-ms: 3000 # 清理无效节点的时间间隔,生产环境不建议配置